export const ALL_FRIENDS_LOADING = 'ALL_FRIENDS_LOADING';
export const ALL_FRIENDS_FETCHED = 'ALL_FRIENDS_FETCHED';
export const MOVE_FRIEND_TO_SELECTED = 'MOVE_FRIEND_TO_SELECTED';
export const MOVE_FRIEND_TO_ALL = 'MOVE_FRIEND_TO_ALL';
export const FILTER_ALL_FRIENDS = 'FILTER_ALL_FRIENDS';
export const FILTER_SELECTED_FRIENDS = 'FILTER_SELECTED_FRIENDS';
